apiVersion: v1
kind: Service
metadata:
  name: fraudguard-inference
  namespace: fraudguard
  labels:
    app: fraudguard-inference
spec:
  selector:
    app: fraudguard-inference
  ports:
    - name: http
      port: 8000
      targetPort: 8000