apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - prometheus.yaml
  - grafana.yaml
  - fraudguard-dashboard-configmap.yaml
  - grafana-datasource-configmap.yaml
  - grafana-dashboard-provider-configmap.yaml

patches:
  - path: grafana-datasource.yaml
  - path: grafana-dashboard-provider.yaml